import { Injectable } from '@nestjs/common';

@Injectable()
export class TermsAndConditionsService {
  getTermsAndConditions() {
    return {
      id: 45,
      creationDate: '2023-09-29T10:25:10.351832200',
      description:
        'Vigencia para realizar compras y diferir al XX de XXXX de XXXX. La promoción es personal e intransferible. El diferido aplica en todas las compras a partir de $X,XXX,XX M.N. por ticket no acumulable que realice durante la vigencia de la promoción, en cualquier comercio previamente validado por el banco, en caso de que alguna de las compras no tenga la opción de diferirse el banco se reserva el derecho de otorgar la promoción.El diferido se verá reflejado máximo 5 días naturales después de la solicitud como un ¿Abono cargo traspasado cuotas" que elimina la compra a un pago y cada mes se reflejará la mensualidad correspondiente como un pago fijo que incluye capital e intereses antes de IVA en el estado de cuenta sección ¿Promociones Meses con Intereses¿. Oferta sujeta a validación del comportamiento crediticio del cliente al momento de hacerla efectiva. Una vez aceptada será irreversible el diferido y el interés salvo que se liquide la totalidad. En caso de cancelar la compra es responsabilidad del cliente llamar a SuperLínea para cancelar el diferido y liquidar el monto restante. Si se presenta un impago o no se paga la cuota completa, los intereses generados por este adeudo se calcularán conforme a la tasa habitual de la tarjeta. Período máximo para solicitar una aclaración 90 días posteriores a la aceptación de la oferta. Promoción abierta a cualquier comercio, nacional y en el extranjero. No aplican tarjetas empresariales y/o corporativas, compras realizadas a Meses Sin Intereses directo en el establecimiento, cargos recurrentes, disposiciones en efectivo, saldos a favor, comisiones ni transferencias. En caso de no solicitar el diferido la compra se verá reflejada en un solo pago, no teniendo carácter retroactivo CAT promedio del diferimiento a 6 meses: CAT 32.9% más IVA, Fecha de cálculo al 1 de Agosto 2023 para fines informativos y de comparación, calculado con compra promedio de $1,000.00 M.N. en promociones de Meses con Intereses, tasa de interés mensual fija de 2.40% que representa una tasa anual fija de 28.8% sin IVA.Sujeto a cambios al momento de formalizar la oferta en Súper Móvil. Aplica a clientes con pagos al corriente. CAT PROMEDIO del portafolio de tarjetas 83.8% Sin IVA. Calculado al 1 de julio del 2023. Tasa de interés promedio ponderada por saldo 63.32% anual variable. Comisión promedio anual $2,923.10 M.N. sin IVA. Los servicios ofrecidos a través de SúperMóvil están catalogados como servicios de banca electrónica y son prestados por Banco Santander México S.A., Institución de Banca Múltiple, Grupo Financiero Santander México. Para mayor información de nuestros productos, comisiones, contrataciones, beneficios del producto, aviso de privacidad y tipsantifraudeconsulta www.santander.com.mxProductos emitidos por Banco Santander México S A Institución de Banca Múltiple, Grupo Financiero Santander México.',
      status: 1,
    };
  }
}
